version: "3.8"

services:

  www:
    build: .
    restart: always
    ports: 
        - "80:80"
    volumes:
        - ./www:/var/www/html/
    links:
        - mysql
    networks:
        - default    

  mysql:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: hamburgueseria
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: davidgg00 
    networks:
        - default  
  


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
  