/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.GestionIngrediente;
import controlador.Validar;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Ingrediente;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DavidGG
 */
public class OpcionesHistorialPedidos extends javax.swing.JFrame {

    public OpcionesHistorialPedidos() {
        initComponents();
        wrapperContent.setBackground(new Color(181, 97, 54, 240));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCreaIngrediente = new javax.swing.JDialog();
        jPanel3 = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcHamburguesas.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelHeader1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        javax.swing.JPanel panelContentCI = new JPanel() {        public void paintComponent(Graphics g) {          Image img = Toolkit.getDefaultToolkit().getImage(          Principal.class.getResource("/imagenes/back_opcHamburguesas.jpg"));          g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);          }        };
        panelFormularioCI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEnviarCrearIngrediente = new javax.swing.JButton();
        etNombre_crearIngrediente = new javax.swing.JTextField();
        dialogEditarIngrediente = new javax.swing.JDialog();
        jPanel4 = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcHamburguesas.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelHeader2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        javax.swing.JPanel panelContentEI = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcHamburguesas.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelFormularioEI = new javax.swing.JPanel();
        etNombre_editarIngrediente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        elegirIngrediente_editar = new javax.swing.JComboBox<>();
        btnEnviarEditarIngrediente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dialogBorrarIngrediente = new javax.swing.JDialog();
        jPanel6 = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcHamburguesas.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelHeader3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        javax.swing.JPanel panelContentBI = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcHamburguesas.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelFormularioBI = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnEnviarBorrarIngrediente = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        etNombre_borrarIngrediente = new javax.swing.JTextField();
        elegirIngrediente_borrar = new javax.swing.JComboBox<>();
        jPanel1 = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcMenus.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelHeader = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        panelContent = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/back_opcIngredientes.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        wrapperContent = new javax.swing.JPanel();
        fechaFin = new javax.swing.JTextField();
        fechaInicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etIdPedido = new javax.swing.JTextField();
        btnPedidoEspecifico = new javax.swing.JButton();
        btnHistorialPedidos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        dialogCreaIngrediente.setMinimumSize(null);
        dialogCreaIngrediente.setResizable(false);
        dialogCreaIngrediente.setSize(new java.awt.Dimension(700, 700));

        jPanel3.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel3.setLayout(new java.awt.BorderLayout());

        panelHeader1.setBackground(new java.awt.Color(130, 93, 46));
        panelHeader1.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Crear Ingrediente");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelHeader1.add(jLabel7, java.awt.BorderLayout.CENTER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goback.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelHeader1.add(jButton5, java.awt.BorderLayout.LINE_END);

        jPanel3.add(panelHeader1, java.awt.BorderLayout.PAGE_START);

        panelContentCI.setBackground(new java.awt.Color(181, 97, 54));
        panelContentCI.setMaximumSize(new java.awt.Dimension(500, 600));
        panelContentCI.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel1.setText("Nombre:");

        btnEnviarCrearIngrediente.setText("Añadir Ingrediente");
        btnEnviarCrearIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCrearIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormularioCILayout = new javax.swing.GroupLayout(panelFormularioCI);
        panelFormularioCI.setLayout(panelFormularioCILayout);
        panelFormularioCILayout.setHorizontalGroup(
            panelFormularioCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioCILayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(etNombre_crearIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(panelFormularioCILayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnEnviarCrearIngrediente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelFormularioCILayout.setVerticalGroup(
            panelFormularioCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioCILayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelFormularioCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etNombre_crearIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)
                .addComponent(btnEnviarCrearIngrediente)
                .addGap(202, 202, 202))
        );

        javax.swing.GroupLayout panelContentCILayout = new javax.swing.GroupLayout(panelContentCI);
        panelContentCI.setLayout(panelContentCILayout);
        panelContentCILayout.setHorizontalGroup(
            panelContentCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentCILayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(panelFormularioCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        panelContentCILayout.setVerticalGroup(
            panelContentCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentCILayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(panelFormularioCI, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jPanel3.add(panelContentCI, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout dialogCreaIngredienteLayout = new javax.swing.GroupLayout(dialogCreaIngrediente.getContentPane());
        dialogCreaIngrediente.getContentPane().setLayout(dialogCreaIngredienteLayout);
        dialogCreaIngredienteLayout.setHorizontalGroup(
            dialogCreaIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogCreaIngredienteLayout.setVerticalGroup(
            dialogCreaIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dialogEditarIngrediente.setMinimumSize(null);
        dialogEditarIngrediente.setResizable(false);
        dialogEditarIngrediente.setSize(new java.awt.Dimension(700, 700));

        jPanel4.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel4.setLayout(new java.awt.BorderLayout());

        panelHeader2.setBackground(new java.awt.Color(130, 93, 46));
        panelHeader2.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Editar Ingrediente");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelHeader2.add(jLabel8, java.awt.BorderLayout.CENTER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goback.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelHeader2.add(jButton3, java.awt.BorderLayout.LINE_END);

        jPanel4.add(panelHeader2, java.awt.BorderLayout.PAGE_START);

        panelContentEI.setBackground(new java.awt.Color(181, 97, 54));
        panelContentEI.setMaximumSize(new java.awt.Dimension(500, 600));

        jLabel12.setText("Nombre:");

        elegirIngrediente_editar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                elegirIngrediente_editarItemStateChanged(evt);
            }
        });

        btnEnviarEditarIngrediente.setText("Editar Ingrediente");
        btnEnviarEditarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEditarIngredienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrediente:");

        javax.swing.GroupLayout panelFormularioEILayout = new javax.swing.GroupLayout(panelFormularioEI);
        panelFormularioEI.setLayout(panelFormularioEILayout);
        panelFormularioEILayout.setHorizontalGroup(
            panelFormularioEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioEILayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelFormularioEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFormularioEILayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(elegirIngrediente_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormularioEILayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(etNombre_editarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioEILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarEditarIngrediente)
                .addGap(138, 138, 138))
        );
        panelFormularioEILayout.setVerticalGroup(
            panelFormularioEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioEILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elegirIngrediente_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etNombre_editarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(126, 126, 126)
                .addComponent(btnEnviarEditarIngrediente)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panelContentEILayout = new javax.swing.GroupLayout(panelContentEI);
        panelContentEI.setLayout(panelContentEILayout);
        panelContentEILayout.setHorizontalGroup(
            panelContentEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentEILayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(panelFormularioEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        panelContentEILayout.setVerticalGroup(
            panelContentEILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentEILayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(panelFormularioEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jPanel4.add(panelContentEI, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout dialogEditarIngredienteLayout = new javax.swing.GroupLayout(dialogEditarIngrediente.getContentPane());
        dialogEditarIngrediente.getContentPane().setLayout(dialogEditarIngredienteLayout);
        dialogEditarIngredienteLayout.setHorizontalGroup(
            dialogEditarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogEditarIngredienteLayout.setVerticalGroup(
            dialogEditarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogBorrarIngrediente.setMinimumSize(null);
        dialogBorrarIngrediente.setResizable(false);
        dialogBorrarIngrediente.setSize(new java.awt.Dimension(700, 700));

        jPanel6.setLayout(new java.awt.BorderLayout());

        panelHeader3.setBackground(new java.awt.Color(130, 93, 46));
        panelHeader3.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Borrar Ingrediente");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelHeader3.add(jLabel13, java.awt.BorderLayout.CENTER);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goback.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelHeader3.add(jButton4, java.awt.BorderLayout.LINE_END);

        jPanel6.add(panelHeader3, java.awt.BorderLayout.PAGE_START);

        panelContentBI.setBackground(new java.awt.Color(181, 97, 54));
        panelContentBI.setPreferredSize(new java.awt.Dimension(609, 603));

        jLabel14.setText("Ingrediente:");

        btnEnviarBorrarIngrediente.setText("Borrar Ingrediente");
        btnEnviarBorrarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarBorrarIngredienteActionPerformed(evt);
            }
        });

        jLabel21.setText("Nombre:");

        etNombre_borrarIngrediente.setEditable(false);

        elegirIngrediente_borrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                elegirIngrediente_borrarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelFormularioBILayout = new javax.swing.GroupLayout(panelFormularioBI);
        panelFormularioBI.setLayout(panelFormularioBILayout);
        panelFormularioBILayout.setHorizontalGroup(
            panelFormularioBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBILayout.createSequentialGroup()
                .addGroup(panelFormularioBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioBILayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel21))
                    .addGroup(panelFormularioBILayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(panelFormularioBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elegirIngrediente_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNombre_borrarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioBILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarBorrarIngrediente)
                .addGap(124, 124, 124))
        );
        panelFormularioBILayout.setVerticalGroup(
            panelFormularioBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elegirIngrediente_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(panelFormularioBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(etNombre_borrarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnEnviarBorrarIngrediente)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout panelContentBILayout = new javax.swing.GroupLayout(panelContentBI);
        panelContentBI.setLayout(panelContentBILayout);
        panelContentBILayout.setHorizontalGroup(
            panelContentBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentBILayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(panelFormularioBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        panelContentBILayout.setVerticalGroup(
            panelContentBILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentBILayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(panelFormularioBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel6.add(panelContentBI, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout dialogBorrarIngredienteLayout = new javax.swing.GroupLayout(dialogBorrarIngrediente.getContentPane());
        dialogBorrarIngrediente.getContentPane().setLayout(dialogBorrarIngredienteLayout);
        dialogBorrarIngredienteLayout.setHorizontalGroup(
            dialogBorrarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogBorrarIngredienteLayout.setVerticalGroup(
            dialogBorrarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBorrarIngredienteLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(130, 93, 46));
        panelHeader.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Opciones Historial Pedidos");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelHeader.add(jLabel6, java.awt.BorderLayout.CENTER);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goback.png"))); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(50, 47));
        jButton6.setMinimumSize(new java.awt.Dimension(50, 47));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 47));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelHeader.add(jButton6, java.awt.BorderLayout.LINE_END);

        jPanel1.add(panelHeader, java.awt.BorderLayout.PAGE_START);

        jLabel5.setText("Fecha Fin");

        jLabel4.setText("Fecha Inicio");

        jLabel3.setText("IdPedido");

        btnPedidoEspecifico.setText("Ver Pedido Específico");
        btnPedidoEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoEspecificoActionPerformed(evt);
            }
        });

        btnHistorialPedidos.setText("Ver historial Pedidos");
        btnHistorialPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialPedidosActionPerformed(evt);
            }
        });

        jLabel9.setText("Dejar vacío si quiere ver historial completo");

        javax.swing.GroupLayout wrapperContentLayout = new javax.swing.GroupLayout(wrapperContent);
        wrapperContent.setLayout(wrapperContentLayout);
        wrapperContentLayout.setHorizontalGroup(
            wrapperContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperContentLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(wrapperContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapperContentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(wrapperContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wrapperContentLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(etIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(wrapperContentLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel3))
                            .addComponent(btnPedidoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(wrapperContentLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(wrapperContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnHistorialPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(wrapperContentLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5))
                    .addGroup(wrapperContentLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4))
                    .addComponent(jLabel9))
                .addGap(104, 104, 104))
        );
        wrapperContentLayout.setVerticalGroup(
            wrapperContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHistorialPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnPedidoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(wrapperContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(wrapperContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel1.add(panelContent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEnviarCrearIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCrearIngredienteActionPerformed


    }//GEN-LAST:event_btnEnviarCrearIngredienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void elegirIngrediente_editarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_elegirIngrediente_editarItemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_elegirIngrediente_editarItemStateChanged

    private void btnEnviarEditarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEditarIngredienteActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEnviarEditarIngredienteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEnviarBorrarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarBorrarIngredienteActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEnviarBorrarIngredienteActionPerformed

    private void elegirIngrediente_borrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_elegirIngrediente_borrarItemStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_elegirIngrediente_borrarItemStateChanged

    private void btnHistorialPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPedidosActionPerformed
        // TODO add your handling code here:
        Connection conectar = null;
        try {
            Class.forName("org.gjt.mm.mysql.Driver");
            conectar = DriverManager.getConnection("jdbc:mysql://localhost/hamburgueseria", "root", "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de conexion de la base de datos");
        }
        try {
            Statement sentencia = conectar.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear el objeto sentencia");
        }

        try {
            String rutaInforme = "reportes\\ReporteHamburgueseria.jasper";
            Map parametros = new HashMap();
            String strFechaInicio = "2000/01/01", strFechaFin = "2500/01/01";
            if (!fechaInicio.getText().isEmpty() && !fechaFin.getText().isEmpty()) {
                if (fechaInicio.getText().matches("\\d{4}-\\d{2}-\\d{2}") && fechaFin.getText().matches("\\d{4}-\\d{2}-\\d{2}")) {
                    strFechaInicio = fechaInicio.getText().toString();
                    strFechaFin = fechaFin.getText().toString();
                } else {
                    JOptionPane.showMessageDialog(null, "El formato de fecha tiene que ser YYYY-MM-DD");
                    return;
                }

            }

            parametros.put("FECHAINI", strFechaInicio);
            parametros.put("FECHAFIN", strFechaFin);
            JasperPrint informe = JasperFillManager.fillReport(rutaInforme, parametros, conectar);

            JasperViewer ventanavisor = new JasperViewer(informe, false);
            ventanavisor.setTitle("Historial Pedidos");
            ventanavisor.setVisible(true);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "error fatgal");
            e.printStackTrace();
        }catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No existen pedidos con ese intervalo de fechas");
        }


    }//GEN-LAST:event_btnHistorialPedidosActionPerformed

    private void btnPedidoEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoEspecificoActionPerformed
        // TODO add your handling code here:
        Connection conectar = null;
        try {
            Class.forName("org.gjt.mm.mysql.Driver");
            conectar = DriverManager.getConnection("jdbc:mysql://localhost/hamburgueseria", "root", "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de conexion de la base de datos");
        }
        try {
            Statement sentencia = conectar.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear el objeto sentencia");
        }

        try {
            String rutaInforme = "reportes\\ReportPedidoHamburgueseria.jasper";
            Map parametros = new HashMap();

            if (!etIdPedido.getText().isEmpty() && Integer.parseInt(etIdPedido.getText().toString()) > 0) {
                parametros.put("IDPEDIDO", etIdPedido.getText().toString());
                JasperPrint informe = JasperFillManager.fillReport(rutaInforme, parametros, conectar);

                JasperViewer ventanavisor = new JasperViewer(informe, false);
                ventanavisor.setTitle("Historial Pedidos");
                ventanavisor.setVisible(true);;
            } else {
                JOptionPane.showMessageDialog(null, "El campo IDPEDIDO es necesario y debe de ser númerico (y positivo)");
            }

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "error fatal al cargar el .jasper");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El campo IDPEDIDO ha de ser numérico");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No existe pedido con ese ID");
        }
    }//GEN-LAST:event_btnPedidoEspecificoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesHistorialPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesHistorialPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesHistorialPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesHistorialPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesHistorialPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarBorrarIngrediente;
    private javax.swing.JButton btnEnviarCrearIngrediente;
    private javax.swing.JButton btnEnviarEditarIngrediente;
    private javax.swing.JButton btnHistorialPedidos;
    private javax.swing.JButton btnPedidoEspecifico;
    private javax.swing.JDialog dialogBorrarIngrediente;
    private javax.swing.JDialog dialogCreaIngrediente;
    private javax.swing.JDialog dialogEditarIngrediente;
    private javax.swing.JComboBox<String> elegirIngrediente_borrar;
    private javax.swing.JComboBox<String> elegirIngrediente_editar;
    private javax.swing.JTextField etIdPedido;
    private javax.swing.JTextField etNombre_borrarIngrediente;
    private javax.swing.JTextField etNombre_crearIngrediente;
    private javax.swing.JTextField etNombre_editarIngrediente;
    private javax.swing.JTextField fechaFin;
    private javax.swing.JTextField fechaInicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelFormularioBI;
    private javax.swing.JPanel panelFormularioCI;
    private javax.swing.JPanel panelFormularioEI;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHeader1;
    private javax.swing.JPanel panelHeader2;
    private javax.swing.JPanel panelHeader3;
    private javax.swing.JPanel wrapperContent;
    // End of variables declaration//GEN-END:variables
}
