/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import modelo.ClientHandler;
import com.AutoBurger.android.Modelo.Pedido;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author DavidGG
 */
public class VerPedidos extends javax.swing.JFrame {

    static String mensaje = "";
    
    /**
     * Creates new form VerPedidos
     */
    public VerPedidos() {
        initComponents();
        System.out.println("a");
       
//        new java.util.Timer().schedule( 
//        new java.util.TimerTask() {
//            @Override
//            public void run() {
//                abrirServerSocket();
//            }
//        }, 
//        5000 
//);
       // abrirServerSocket();
        
    }

    public static void abrirServerSocket(){
        
    InputStreamReader isr;
        BufferedReader br;
        
        ServerSocket serverSocket = null;
        
        try {
            serverSocket = new ServerSocket(8000);
        } catch (IOException ex) {
            Logger.getLogger(VerPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while (true) {
            Socket socket = null;
            try {

                System.out.println("entro");
                socket = serverSocket.accept();

                ObjectInputStream objectInputStream = new ObjectInputStream(socket.getInputStream());
                Pedido cuentaRecibido = (Pedido) objectInputStream.readObject();

                Thread nuevoHilo = new ClientHandler(socket, new DataInputStream(socket.getInputStream()), new DataOutputStream(socket.getOutputStream()), cuentaRecibido);

                nuevoHilo.start();
               

            } catch (Exception e) {
                e.printStackTrace();
            }
        }    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPedidos = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    VerPedidos.class.getResource("/imagenes/background_pedidosPendientes.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        panelHeader = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelContent = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Principal.class.getResource("/imagenes/background_pedidosPendientes.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPedidos.setMaximumSize(new java.awt.Dimension(800, 500));
        panelPedidos.setMinimumSize(new java.awt.Dimension(800, 500));
        panelPedidos.setPreferredSize(new java.awt.Dimension(800, 500));
        panelPedidos.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(130, 93, 46));
        panelHeader.setPreferredSize(new java.awt.Dimension(786, 84));
        panelHeader.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pedidos Pendientes");
        jLabel6.setMinimumSize(null);
        panelHeader.add(jLabel6, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goback.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelHeader.add(jButton1, java.awt.BorderLayout.EAST);

        panelPedidos.add(panelHeader, java.awt.BorderLayout.NORTH);

        panelContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        panelPedidos.add(panelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPedidos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // Principal p = new Principal(false);
       //p.setVisible(true);
      // p.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPedidos().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    public static javax.swing.JPanel panelPedidos;
    // End of variables declaration//GEN-END:variables
}
